#!/usr/bin/perl 
#
#
# TODO:
# 	21/nov/2005 - If a location is not specified on the command line, this 
# 		      command should run in "daemon" mode: look if there are newly
# 		      added location by MetaInfoAddLocation command and index them,
# 		      update the current indexes.

use strict;
use lib $ENV{FILEMETAINFO_LIBDIR};
use Cwd qw(abs_path);
use Getopt::Long;
use Carp;
use File::Basename;
use File::FTS;
use File::MetaInfo::DB;
use File::MetaInfo;
use Time::HiRes;
use Data::Dumper;

my $NAME="MetaInfoUpdateDB";

my $debug;
my $measure;
my $basedir;
my @filelist;
my $step=1000;
my $ret;
my $daemon;
my $cdrom;
my $volname;
my $cddev;
my $mpoint;
my $mounted;
my $volid=undef;
my $exclude;
my %excl;
my $exp;
my $verbose;
my $quiet;
my $force;
my ($a,$u,$s)=(0,0,0);
my $i=0;


GetOptions(
	"debug+" => \$debug,
	"measure" => \$measure,
	"step=n" => \$step,
	"cdrom" => \$cdrom,
	"verbose" => \$verbose,
	"volume-name=s" => \$volname,
	"exclude-list=s" => \$exclude,
	"exclude-pattern=s" => \$exp,
	"quiet" => \$quiet,
	"force" => \$force
);
print "DEBUG Level: $debug\n" if $debug;
my $fdb=new File::MetaInfo::DB( debug=> ($debug-2));

my $t0=Time::HiRes::time;

if ($#ARGV lt 0){
	die "You must specify at least one directory to start indexing\n";
}

foreach $basedir (@ARGV){

	$basedir || die "FATAL: You must specify a directory tree to add to the File::MetaInfo::DB";

	if ($cdrom){
		$volname || die "Fatal: You should specify a volume name";
		use File::MetaInfo::Volume::CD;
		$cddev=File::MetaInfo::Volume::CD::device($basedir);
		$mpoint=File::MetaInfo::Volume::CD::mount_point($cddev);
		$mounted=File::MetaInfo::Volume::CD::is_mounted($cddev);
		if (!$mounted){
			`mount $mpoint`;
			$mounted=File::MetaInfo::Volume::CD::is_mounted($cddev);
			die "Fatal: Could not mount device $cddev" unless ($mounted eq 1);
		}
		my ($id,$last,$lenght,$toc)=File::MetaInfo::Volume::CD::get_discids($cddev);
		$volid="$id-$last-$lenght";
		$fdb->add_volume($volid,$volname) || warn "Warning: Could not add volume $@";
	}
	
	if (defined($exclude)){
		my @list=split(/[, \n]/,$exclude);
		foreach (@list){
			$excl{$_}=1;
		}
	}

	$basedir=abs_path($basedir);
	warn "DEBUG: basedir=$basedir\n" if $debug;
	if ( -d $basedir ){
		print "\nImporting directory $basedir\n";
		my $fts=new File::FTS($ARGV[0]);
		while (my $file = $fts->Dive){
			add_it($file);
		}
	} 
	elsif ( -f $basedir ){
		print "\nImporting file $basedir\n";
		add_it($basedir);
	}
	$fdb->commit();
}
print "\nProcessed $i files. ";
my $tf=Time::HiRes::time;
my $time=($tf - $t0);
print "\nDone: processed $i files in: $time \n";
print "Filename: " . $fdb->get_dbfilename() . "\n";
print "Addedd: $a\n";
print "Updated: $u\n";
print "Skipped: $s\n";
$fdb->close();


#############
#
sub add_it{
	my $fn=shift;
	warn "DEBUG: main::add_it::filename=$fn - @_\n" if $debug;
	print "$fn->" if $verbose;
	if (defined($excl{$fn}) || (defined($exp) and $fn =~ /$exp/) ){
		print "S" if (!defined($quiet));
		$s++;
		print "\n" if $verbose;
		return;
	}

	$fdb->begin_work() if (($i % $step) eq 0);
	my $finfo=new File::MetaInfo(
			$fn,
			fileInfoDB=>$fdb,
			volumeid=>$volid,
			excludeKeywords=>"File::MetaInfo::Plugins::Extract.filename",
			debug=>($debug-1),
			normalize=>1
			) || die;
	print "." if (!defined($quiet));
	if($finfo->{fresh}){
		print "\bA" if (!defined($quiet));
		$a++;
	}
	elsif($finfo->changed() || defined($force)){
		$finfo->update();
		print "\bU" if (!defined($quiet));
		$u++;
	}
	$i++;
	$fdb->commit() if (($i % $step) eq 0);
	print "c" if (($i % $step) eq 0) and (!defined($quiet));
	print "\n" if $verbose
}

