FILEMETAINFO_BASEDIR=/home/fl118890/Documents/developement/file-metainfo/trunk
FILEMETAINFO_LIBDIR=${FILEMETAINFO_BASEDIR}/lib
FILEMETAINFO_UIDIR=${FILEMETAINFO_BASEDIR}/glade
export FILEMETAINFO_UIDIR FILEMETAINFO_LIBDIR FILEMETAINFO_BASEDIR

PATH=$PATH:$FILEMETAINFO_BASEDIR/scripts
export PATH
