#!/usr/bin/perl 
#

use strict;
use lib $ENV{FILEMETAINFO_LIBDIR};
use File::MetaInfo;
use File::MetaInfo::DB;
use Data::Dumper;
use Getopt::Long;

our $NAME="MetaInfoSearch";
our $VERSION="0.1";
our $USAGE=
"Usage: $NAME [options] KEYWORDS
Search your File::MetaInfo DB for files matching the KEYWORD.
Your DB is located under \'$File::MetaInfo::DB::defaultlocation\'.

Options:
  -b, --brief 	  Show only the full path (as locate do)
  -l, --long 	  Show also other informations about the files found
  -m, --matching  In 'brief' mode print matching keywords
  -k, --keywords  Search the term in all the keywrod. Default searches in users keywords only.

  -t, --times 	Show times
  -d, --debug
  -n, --nokeywords
  -g, --gnome-vfs
";

my ($s,$m);
my $debug=0;
my $brief=0;
my $long=1;
my $match=0;
my $keywords=0;
my $gnome;
my @nokeys;
my $help;

GetOptions(
	"times" => \$m,
	"debug+" => \$debug,
	"nokeywords=s" => \@nokeys,
	brief => \$brief,
	long => \$long,
	'gnome-vfs' => \$gnome,
	matching => \$match,
	help => \$help,
	keywords=> \$keywords
);


my $value=shift;

if ($help || !defined($value)){
	print $USAGE;
	exit 0
}
my $fdb=new File::MetaInfo::DB( debug => $debug) || die "Could not open DB\n";

my $t0=Time::HiRes::time if ($m);

my $arrayref;

if ($keywords){
	$arrayref=$fdb->search_full($value);
}
else {
	my $kv={
		keyword=> $File::MetaInfo::UserLabel,
		value => "$value"
	};
	$arrayref=$fdb->search_keyval($kv);
}

my $tf=Time::HiRes::time if ($m);
warn "TIMES: search() elapsed in " . ($tf - $t0) . " seconds\n" if ($m);
print Dumper($arrayref) if $debug;
$t0=Time::HiRes::time if ($m);
foreach (@$arrayref){
	print "DEBUG: $$_[0]\n" if $debug;
	#my $tn0=Time::HiRes::time if ($m);
	my $fi=new File::MetaInfo(
		 $$_[0],
	 	 fileInfoDB => $fdb,
	 	 debug => $debug
	) || die "Could not instantiate File::MetaInfo: $@\n";
	#my $tnf=Time::HiRes::time if ($m);
	#warn "TIMES: File::MetaInfo::new() elapsed in " . ($tnf - $tn0) . " seconds\n" if ($m);
	if ($brief){
		print $fi->{fullpath};
		if ($match){
			print " [" . $fi->sprintf_matching_keywords($value) . "]";
		}
		print "\n";
	}
	else{
	 	$fi->print_info(": ");
	 	print "Keywords:\n\t";
	 	$fi->print_values(":\t","\n\t",",",$value);
		if ($gnome){
			print "VFS Info:\n";
			$fi->print_gnome2_info();
		}
	 	print "\n";

	}
	#$fi->close();
}

$tf=Time::HiRes::time if ($m);
warn "TIMES: total rendering time: " . ($tf - $t0) . " seconds\n" if ($m);
$fdb->close();
