#!/usr/bin/perl 
#

use strict;
use Data::Dumper;
use Getopt::Long;

use lib $ENV{FILEMETAINFO_LIBDIR};
use File::MetaInfo;
use File::MetaInfo::DB;
use File::MetaInfo::Utils;
use File::MetaInfo::Query::Simple;

our $NAME="MetaInfoSearch";
our $VERSION="0.2";
our $USAGE=
"Usage: $NAME [options] [KEYWORD:]LABEL
Search your File::MetaInfo DB for files matching the LABEL. If KEYWORD is 
specified the search is done only for the specified one. You can specify an 
asterisk '*' to search in all the keywords. Default is to search in 
'$File::MetaInfo::UserLabel'.
Your DB is located under \'$File::MetaInfo::DB::defaultlocation\'.

Options:
  -b, --brief 	  Show only the full path (as locate do)
  -l, --long 	  Show also other informations about the files found
  -m, --matching  In 'brief' mode print matching keywords

  -t, --times 	Show times
  -d, --debug
  -n, --nokeywords
  -g, --gnome-vfs
";

my ($s,$m);
my $debug=0;
my $brief=0;
my $long=1;
my $match=0;
my $gnome;
my @nokeys;
my $help;

GetOptions(
	"times" => \$m,
	"debug+" => \$debug,
	"nokeywords=s" => \@nokeys,
	brief => \$brief,
	long => \$long,
	'gnome-vfs' => \$gnome,
	matching => \$match,
	help => \$help,
);


my $value=shift;

if ($help || !defined($value)){
	print $USAGE;
	exit 0
}
my $fdb=new File::MetaInfo::DB( debug => $debug) || die "Could not open DB\n";

my $timer=File::MetaInfo::Utils::start_timer();

my $fmiq=new File::MetaInfo::Query::Simple(
	$value,
	debug => $debug,
	measure => $m
) || die "Fatal: could not instantiate the query object";

$fmiq->run();

warn "TIMES: search() elapsed in " . File::MetaInfo::Utils::stop_timer($timer) . " seconds\n" if ($m);
print Dumper($fmiq) if $debug;

$timer=File::MetaInfo::Utils::start_timer();

#$fmiq->matching_keyword;
foreach my $id (keys %{$fmiq->{results}}){

	my $fi=$fmiq->{results}->{$id};

	if ($brief){
		print "$fi->{fullpath}";
		if ($match){
			print " [". $fi->sprintf_matching($fmiq->{keyword},$fmiq->{value}) . "]";
		}
		print "\n";
	}
	else{
		print "#####################\n";
	 	$fi->print_info(": ");
	 	print "Keywords:\n\t";
	 	$fi->print_values(":\t","\n\t",",",1);
		if ($gnome){
			print "VFS Info:\n";
			$fi->print_gnome2_info();
		}
	 	print "\n";

	}
	#$fi->close();
}

warn "TIMES: total rendering time: " . File::MetaInfo::Utils::stop_timer($timer) . " seconds\n" if ($m);
$fmiq->close();
