FILEMETAINFO_BASEDIR=/home/shared/developement/file-metainfo/trunk
FILEMETAINFO_LIBDIR=${FILEMETAINFO_BASEDIR}/lib
FILEMETAINFO_UIDIR=${FILEMETAINFO_BASEDIR}/glade
export FILEMETAINFO_UIDIR FILEMETAINFO_LIBDIR FILEMETAINFO_BASEDIR
